services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,dynamodb,lambda,logs,cloudwatch,xray
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- }
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./localstack/default-schemas.json:/etc/localstack/init/ready.d/default-schemas.json"
      - "./build:/var/task"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack